config/routes.rb
Rails.application.routes.draw do
  resources :documents

  devise_for :admins

  get "admins/menu" => "admins#index"

  devise_scope :admin do
    root :to => 'devise/sessions#new'
  end

  devise_for :students, controllers: { registrations: "students/registrations" }

  namespace :students do
    resources :accounts
    get 'accounts/acknowledge_student/:id' => 'accounts#acknowledge_student', as: :accounts_acknowledge
    get 'accounts/acknowledge_fee/:id' => 'accounts#acknowledge_fee', as: :accounts_acknowledge_fee
  end

  namespace :api do
    devise_scope :student do
      post 'sessions' => 'sessions#create', as: :student_login
      delete 'sessions' => 'sessions#destroy', as: :student_logout
    end
    post 'tasks' => 'tasks#index', :as => 'tasks'
  end
  

end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :token_authenticatable,
         :rememberable, :trackable, :validatable

  before_save :ensure_authentication_token
  
end

app/controllers/students/accounts_controller.rb
class Students::AccountsController < ApplicationController
	before_action :authenticate_admin!
	def index
		@students = Student.all.order(fee_acknowledgement: :asc, acknowledged_at: :asc).page(params[:page]).per(25)
	end

	def acknowledge_student
		@student = Student.find(params[:id])
		
		if @student.update_attributes(acknowledged_at: Time.now)
			flash[:notice] = "Student ID: #{@student.id} (Student #{@student.name}) has been acknowledged to receive the application."
		else
			flash[:danger] = "Failed to acknowledge student."
		end		
		redirect_to students_accounts_path
	end

	def acknowledge_fee
		@student = Student.find(params[:id])
		
		if @student.update_attributes(fee_acknowledgement: Time.now)
			flash[:notice] = "Student ID: #{@student.id} (Student #{@student.name}) has acknowledged the Fee Schedule."
		else
			flash[:danger] = "Failed to update student's fee acknowledgement status."
		end		
		redirect_to students_accounts_path
	end

	private

	def student_params
		params.require(:student).permit(:name, :email, :password, :password_confirmation, :remember_me)
	end
end

app/helpers/students/accounts_helper.rb
module Students::AccountsHelper
end

app/views/students/accounts/index.html.erb
<h1>View Students' Record</h1>

<div class="text-center">
	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th style="text-align:center">Student ID</th>
				<th style="text-align:center">Name</th>
				<th style="text-align:center">Email Address</th>
				<th style="text-align:center">Intake Code</th>
				<th style="text-align:center">Orientation Pack Acknowledgement</th>
				<th style="text-align:center">Fee Schedule Acknowledgement</th>
			</tr>
		</thead>

		<% @students.each do |s| %>
			<tr>
				<td><%= s.username %></td>
				<td><%= s.name %></td>
				<td><%= s.email %></td>
				<td><%= s.intake_code %></td>			
				<td>
					<% if s.acknowledged_at.nil? %>
						<%= link_to "Acknowledge Now", students_accounts_acknowledge_path(s),
								data: { confirm: "Are you sure to acknowledge that #{s.name}" + 
												 " (#{s.username}) has received the Orientation Pack?" } %>
					<% else %>
						<%= I18n.l s.acknowledged_at, format: :short %>
					<% end %>
				</td>
				<td>
					<% if s.fee_acknowledgement.nil? %>
						<%= link_to "Submitted Fee Schedule Acknowledgement Form", students_accounts_acknowledge_fee_path(s),
								data: { confirm: "Are you sure to acknowledge that #{s.name}" + 
												 " (#{s.username}) has submitted the Fee Schedule Acknowledgement Form?" } %>
					<% else %>
						<%= I18n.l s.fee_acknowledgement, format: :short %>
					<% end %>
				</td>
			</tr>
		<% end %>
	</table>
	<center><%= paginate @students %></center>
</div>
<%= link_to "Back", admins_menu_path, class: "btn btn-default btn-md" %>