config/routes.rb
Rails.application.routes.draw do
  resources :documents

  devise_for :admins

  get "admins/menu" => "admins#index"

  devise_scope :admin do
    root :to => 'devise/sessions#new'
  end

  devise_for :students, controllers: { registrations: "students/registrations" }

  namespace :students do
    resources :accounts
    get 'accounts/acknowledge_student/:id' => 'accounts#acknowledge_student', as: :accounts_acknowledge
    get 'accounts/acknowledge_fee/:id' => 'accounts#acknowledge_fee', as: :accounts_acknowledge_fee
  end

  namespace :api do
    devise_scope :student do
      post 'sessions' => 'sessions#create', as: :student_login
      delete 'sessions' => 'sessions#destroy', as: :student_logout
    end
    post 'tasks' => 'tasks#index', :as => 'tasks'
  end
  

end

app/models/document.rb
class Document < ActiveRecord::Base
	mount_uploader :document_url, FileUploader

	validates :name, :document_url, :intake_code, presence: true
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate!

  require 'carrierwave/orm/activerecord'
  
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all.order(intake_code: :desc).page(params[:page]).per(8)
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
    @document_type = "Student Handbook"
  end

  # GET /documents/1/edit
  def edit
    @document_type = set_document.document_type
  end

  # POST /documents
  # POST /documents.json
  def create    
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to documents_path, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: document_path }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to documents_path, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: documents_path }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:name, :document_type, :document_url, :intake_code)
    end

    def authenticate!
      unless student_signed_in? || admin_signed_in?
        flash[:alert] = "Please login before accessing this page."
        redirect_to root_path
      end
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
  <%= form_for(@document) do |f| %>
    <% if @document.errors.any? %>
      <div class="alert alert-danger" role="alert"> 
        <h3><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h3>
        <ul>        
          <% @document.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>


    <div class="form-group">
      Document Name: <%= f.text_field :name, placeholder: "Name of the Document",
                          class: "form-control"  %>
      </div>  
    
    <br/>

    <div class="form-group">
      Document Type: 
        <%= f.select(:document_type,  [['Student Handbook', 'Student Handbook'], 
                                ['Orientation Schedule', 'Orientation Schedule'],
                                ['Fee Schedule', 'Fee Schedule'],
                                ['Important Details', 'Important Details']],
                                { selected: @document_type}, 
                                {class: "btn btn-default dropdown-toggle", :'data-toggle' => 'dropdown'}) %>
    </div>

    <br/>

    <div class="form-group">
      <div class = "btn-group">
        Upload Document: <%= f.file_field :document_url, accept: ".pdf" %>
      </div>
    </div>

    <br/>
    
    <div class="form-group">
      Intake Code: <%= f.text_field :intake_code, placeholder: "Intake Code of Students Viewing the Document", 
                        class: "form-control"  %>
    </div>

    <br/>
    
    <div class="form-group">
        <div class="btn-group", role="button">
          <%= f.submit "Save Document", class: "btn btn-info btn-md" %>
    </div>
  <% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form' %>

<%= link_to 'Destroy', @document, method: :delete, data: { confirm: 'Are you sure?' }, 
	class: "btn btn-danger btn-md", style: "color:white" %> 
<%= link_to 'Back', documents_path, class: "btn btn-default btn-md" %>

app/views/documents/index.html.erb
<h1>Listing Documents</h1>

<div class="text-center">
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th style="text-align:center">Document ID</th>
      <th style="text-align:center">Document Name</th>
      <th style="text-align:center">Document Type</th>
      <th style="text-align:center">Document URL</th>
      <th style="text-align:center">Date Added</th>
      <th style="text-align:center">Last Modified</th>
      <th style="text-align:center">Intake</th>
      <th style="text-align:center" colspan="3">Document Action</th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |d| %>
      <tr>
        <td><%= d.id %></td>
        <td><%= d.name %></td>
        <td><%= d.document_type %></td>
        <td><%= d.document_url %></td>
        <td><%= I18n.l d.created_at, format: :short %></td>
        <td><%= I18n.l d.updated_at, format: :short %></td>
        <td><%= d.intake_code %></td>
        <td><%= link_to "Show", d.document_url.to_s, target: :_blank %></td>
        <td><%= link_to 'Edit', edit_document_path(d) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<center><%= paginate @documents %></center>
</div>
<br>

<%= link_to 'New Document', new_document_path, class: "btn btn-success btn-md", style: "color:white" %>
<%= link_to "Back", admins_menu_path, class: "btn btn-default btn-md" %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_menu_path, class: "btn btn-default btn-md" %>

app/views/documents/show.html.erb
<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>