config/routes.rb
Rails.application.routes.draw do
  resources :documents

  devise_for :admins

  get "admins/menu" => "admins#index"

  devise_scope :admin do
    root :to => 'devise/sessions#new'
  end

  devise_for :students, controllers: { registrations: "students/registrations" }

  namespace :students do
    resources :accounts
    get 'accounts/acknowledge_student/:id' => 'accounts#acknowledge_student', as: :accounts_acknowledge
    get 'accounts/acknowledge_fee/:id' => 'accounts#acknowledge_fee', as: :accounts_acknowledge_fee
  end

  namespace :api do
    devise_scope :student do
      post 'sessions' => 'sessions#create', as: :student_login
      delete 'sessions' => 'sessions#destroy', as: :student_logout
    end
    post 'tasks' => 'tasks#index', :as => 'tasks'
  end
  

end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	    <ul class="nav navbar-nav navbar-left">
	    	<li>
	    		<%= link_to image_tag("http://res.cloudinary.com/apuorientation/image/upload/c_scale,h_35/v1426731720/APU%20Logo.png", 
	    							  alt: "APU Logo"), admins_menu_path %>
    		</li>				
	    </ul>
		<ul class="nav navbar-nav navbar-right">
			<% if admin_signed_in? %>
			<li style="padding-bottom: 15px; padding-top: 16px;">Welcome, Admin!</li>
			<li><%= link_to "Sign Out", destroy_admin_session_path, method: :delete %></li>
		<% else %>
			<li><%= link_to "Sign In", new_admin_session_path %></li>
		<% end %>
		</ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApuOrientation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<%= render 'layouts/nav' %>
	<div class="container-fluid">	
		<% unless notice.nil? %>
			<div class="alert alert-success" role="alert">
				<%= notice %>
			</div>
		<% end %>

		<% unless alert.nil? %>
			<div class="alert alert-danger" role="alert">
				<%= alert %>
			</div>
		<% end %>

		<div class="container-fluid">
			<%= yield %>
		</div>
	</div>
</body>
</html>